import "../styles/globals.css";
import { Nunito } from "next/font/google";
import AuthWrapper from "@/utils/authWrapper";

const nunito = Nunito({ subsets: ["latin"] });

export const metadata = {
  title: "Admin Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AuthWrapper>
        <body className={nunito.className}>{children}</body>
      </AuthWrapper>
    </html>
  );
}
